---

# java constants
javax_mail_url: "https://java.net/projects/javamail/downloads/download/javax.mail.jar"

# tomcat constants

tomcat_packages:
 - tomcat8
 - tomcat8-admin

tomcat_extra_packages:
  - libjglobus-jsse-java
  - libjglobus-ssl-proxies-java
  - libjglobus-ssl-proxies-tomcat-java

tomcat_extra_libs: /usr/share/java/jglobus

catalina_home: /var/lib/tomcat8
tomcat_user: tomcat8
tomcat_service: tomcat8

# apache

httpd_packages:
  - apache2
  - apache2-utils

httpd_service: apache2

# mysql

mysql_packages:
  - mysql-server
  - libmysql-java
  - python-mysqldb

mysql_root_password: changeme
mysql_connector_path: /usr/share/java
mysql_connector: mysql-connector-java.jar


# mariadb

# NOTE
# THE MARIADB PACKAGES ARE IN THE CENTOS7 REPOS, BUT THERE IS NO MARIADB JDBC CONNECTOR PROVIDED
# THE CONNECTOR DOWLOADED FROM THE OFFICIAL MARIADB WEBPAGE DOES NOT WORK PROPERLY ON CENTOS7
# THEREFOR WE USE THE CONNECTOR PROVIDED BY MYSQL INSTEAD.

# THE ABOVE EFFECTIVELY MEANS THAT OA4MP WILL RUN WITH 'MYSQL' CONNECTOR AND IMPLEMENTATION
# BUT THE UNDERLYING DATABASE WILL ACTUALLY BY MARIADB.

mariadb_packages:
  - mariadb
  - mariadb-server
  - mysql-connector-java
  - MySQL-python

mariadb_connector_path: /usr/share/java
mariadb_connector: mysql-connector-java.jar

# postgresql

postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-jdbc
  - python-psycopg2

postgresql_connector_path: /usr/share/java
postgresql_connector: postgresql-jdbc.jar
                                           
