---

- name: restart tomcat
  service:
    name: "{{ tomcat_service }}"
    state: restarted

- name: restart httpd
  service:
    name: "{{ httpd_service }}"
    state: restarted

- name: restart iptables
  service:
    name: netfilter-persistent
    state: restarted

- name: restart ip6tables
  service:
    name: netfilter-persistent
    state: restarted

