---

- name: adding IGTF GPG key
  apt_key:
    url: "{{ igtfkey }}"
    state: present

#- name: adding IGTF repository (current-new)
#  yumrepo:
#    name: eugridpma
#    description: EUGridPMA
#    baseurl: "{{ igtf_current_baseurl }}"
#    file: eugridpma
#    gpgcheck: yes
#    enabled: yes
#    gpgkey: "{{ igtfkey }}"

- name: adding IGTF repository (current-new)
  template:
    src: eugridpma.deb.repo.j2
    dest: /etc/apt/sources.list.d/eugridpma.list
    owner: "root"
    group: "root"
    mode: 0644

