---

# Install apache

- name: install httpd
  apt: name={{item}} state=present
  with_items: "{{ httpd_packages }}"

# configure

- name: enable mod headers
  apache2_module:
    state: present
    name: headers

- name: enable mod proxy
  apache2_module:
    state: present
    name: proxy

- name: enable mod proxy_ajp
  apache2_module:
    state: present
    name: proxy_ajp

- name: enable mod ssl
  apache2_module:
    state: present
    name: ssl

- name: httpd config file present
  template:
    src: ssl.conf.j2
    dest: /etc/apache2/mods-available/ssl.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

- name: httproxy config present
  template:
    src: 00-httpoxy.conf.j2
    dest: /etc/apache2/conf-available/httproxy.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

- name: enable httproxy config
  command: /usr/sbin/a2enconf httproxy

# replace welcome page

- name: replace apache welcome page
  stat:
    path: /var/www/html/index.html
  ignore_errors: yes
  register: index_page

- name: create index page
  file:
    path: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    state: touch
  when: index_page.stat.exists == false
