---

# iptables rules for masterportal

- name: add iptables config
  template:
    src: iptables.j2
    dest: "/etc/iptables/rules.v4"
    owner: "root"
    group: "root"
    mode: 0600
    backup: yes
  notify: restart iptables

- name: add ip6tables config
  template:
    src: ip6tables.j2
    dest: "/etc/iptables/rules.v6"
    owner: "root"
    group: "root"
    mode: 0600
    backup: yes
  notify: restart ip6tables
