###              ENVIRONMENT SPECIFIC INFORMATION                 ###
###                                                               ###
### Usually you would override these using a variables include    ###
### file, using the vars_files include in your play. These        ###
### varabales include, for example, passwords, secrets and other  ###
### environment specific information                              ###

# Trust root for the host credential. It can be provided either 
# via an deb package or a PEM formatted file together with a 
# signing policy. The two options are not exclusive, and can
# be used independently of eachother.

# Name of the deb package to install as trust anchor. This ca be
# a link to an deb or a package name from an installed repository
hostcred_trust_anchor_package: "ca-terena-escience-ssl-ca-3"

# Alternatively, the trust anchor can be installed from a PEM
# formatted certificate file accompanied by the signign policy
#hostcred_trust_anchor_pem: "cacert.pem"
#hostcred_trust_anchor_signing_policy: "cacert.signing_policy"

# NTP Server
ntp_servers: 
   - ntp1.server.com
   - ntp2.server.com
